// Code generated by webprotocolgen. DO NOT EDIT.

package web

func unaryRouteHandler(path string) (unaryHandler, bool) {
	switch path {
	case "agent-preset/apply":
		return (*Server).agentPresetApply, true
	case "agent-preset/delete":
		return (*Server).agentPresetDelete, true
	case "agent-preset/list":
		return (*Server).agentPresetList, true
	case "agent-preset/save":
		return (*Server).agentPresetSave, true
	case "agent/list":
		return (*Server).agentList, true
	case "checkpoint/fork":
		return (*Server).checkpointFork, true
	case "checkpoint/get":
		return (*Server).checkpointGet, true
	case "checkpoint/list":
		return (*Server).checkpointList, true
	case "checkpoint/restore":
		return (*Server).checkpointRestore, true
	case "connection/status":
		return (*Server).connectionStatus, true
	case "credential/clear-keyring":
		return (*Server).credentialClearKeyring, true
	case "credential/set-keyring":
		return (*Server).credentialSetKeyring, true
	case "credential/status":
		return (*Server).credentialStatus, true
	case "credential/validate":
		return (*Server).credentialValidate, true
	case "extension/control":
		return (*Server).extensionControl, true
	case "extension/list":
		return (*Server).extensionList, true
	case "mcp/health":
		return (*Server).mcpHealth, true
	case "model/add":
		return (*Server).modelAdd, true
	case "model/list":
		return (*Server).modelList, true
	case "model/probe":
		return (*Server).modelProbe, true
	case "model/remove":
		return (*Server).modelRemove, true
	case "model/test":
		return (*Server).modelTest, true
	case "model/update":
		return (*Server).modelUpdate, true
	case "operation/submit":
		return (*Server).operationSubmit, true
	case "plan/get":
		return (*Server).planGet, true
	case "profile/get":
		return (*Server).profileGet, true
	case "profile/update":
		return (*Server).profileUpdate, true
	case "provider/list":
		return (*Server).providerList, true
	case "session/activate":
		return (*Server).sessionActivate, true
	case "session/create":
		return (*Server).sessionCreate, true
	case "session/delete":
		return (*Server).sessionDelete, true
	case "session/export":
		return (*Server).sessionExport, true
	case "session/history":
		return (*Server).sessionHistory, true
	case "session/list":
		return (*Server).sessionList, true
	case "session/merge":
		return (*Server).sessionMerge, true
	case "session/snapshot":
		return (*Server).sessionSnapshot, true
	case "session/status":
		return (*Server).sessionStatus, true
	case "session/update":
		return (*Server).sessionUpdate, true
	case "setup/apply":
		return (*Server).setupApply, true
	case "setup/probe":
		return (*Server).setupProbe, true
	case "system/describe":
		return (*Server).systemDescribe, true
	case "system/diagnostics":
		return (*Server).systemDiagnostics, true
	case "system/readiness":
		return (*Server).systemReadiness, true
	case "tool/catalog":
		return (*Server).toolCatalog, true
	case "trace/query":
		return (*Server).traceQuery, true
	case "turn/queue":
		return (*Server).turnQueue, true
	case "turn/recover":
		return (*Server).turnRecover, true
	case "usage/query":
		return (*Server).usageQuery, true
	case "workspace/add":
		return (*Server).workspaceAdd, true
	case "workspace/browse":
		return (*Server).workspaceBrowse, true
	case "workspace/diagnostics":
		return (*Server).workspaceDiagnostics, true
	case "workspace/diff":
		return (*Server).workspaceDiff, true
	case "workspace/git-action":
		return (*Server).workspaceGitAction, true
	case "workspace/git-diff":
		return (*Server).workspaceGitDiff, true
	case "workspace/git-status":
		return (*Server).workspaceGitStatus, true
	case "workspace/git-switch":
		return (*Server).workspaceGitSwitch, true
	case "workspace/image":
		return (*Server).workspaceImage, true
	case "workspace/list":
		return (*Server).workspaceList, true
	case "workspace/remove":
		return (*Server).workspaceRemove, true
	case "workspace/resource":
		return (*Server).workspaceResource, true
	case "workspace/search":
		return (*Server).workspaceSearch, true
	case "workspace/select-directory":
		return (*Server).workspaceSelectDirectory, true
	case "workspace/symbols":
		return (*Server).workspaceSymbols, true
	default:
		return nil, false
	}
}
